import type { Metadata } from "next";
import { Bebas_Neue, Lora } from "next/font/google";
import "./globals.css";

const bebasNeue = Bebas_Neue({
      weight: "400",
      subsets: ["latin"],
      variable: "--font-bebasNeue",
});

const lora = Lora({
      subsets: ["latin"],
      variable: "--font-lora", // ✅ corregido
});


export const metadata: Metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
};

export default function RootLayout({
      children,
}: Readonly<{
      children: React.ReactNode;
}>) {
      return (
            <html
            id="home"
                  lang="en"
                  className={`${bebasNeue.variable} ${lora.variable} text-text antialiased scroll-smooth`}
            >
                  <body className="h-full">{children}</body>
            </html>
      );
}
